# Generated by Django 3.0.5 on 2020-04-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bank_number',
            field=models.IntegerField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='credit_card',
            field=models.IntegerField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
